export const certifications = [
    {
      id: 1,
      title: "Digital Marketing",
      issuedBy: "Kemnaker RI DisnakertransDIY at Solusi247",
      date: "2023",
      image: "/images/cert-1.png",
    },
    {
      id: 2,
      title: "Entrpreneurship, IoT & AI",
      issuedBy: "Telkom Digistar",
      date: "2023",
      image: "/images/cert-2.jpeg",
    },
    {
      id: 3,
      title: "Full-Stack Developer ",
      issuedBy: "BelajarKoding Collaboration BWA",
      date: "2022",
      image: "/images/cert-3.png",
    },
    {
      id: 4,
      title: "How To Build A Responsive Web",
      issuedBy: "Insight Mercu Buana Yogyakarta",
      date: "2021",
      image: "/images/cert-4.png",
    },
    {
      id: 5,
      title: "Sentiment Mining",
      issuedBy: "Workshop Colaboration UMBY & UNIKL MIIT",
      date: "2021",
      image: "/images/cert-5.png",
    },
    {
      id: 6,
      title: "UI/UX Figma",
      issuedBy: "Insight Mercu Buana Yogyakarta",
      date: "2021",
      image: "/images/cert-6.png",
    },
    {
      id: 7,
      title: "Artificial Intelligence",
      issuedBy: "Virtual Innovation Summit",
      date: "2021",
      image: "/images/cert-7.png",
    },
    {
      id: 8,
      title: "React Course",
      issuedBy: "Progate",
      date: "2021",
      image: "/images/cert-8.png",
    },
    {
      id: 9,
      title: "Sass Course",
      issuedBy: "Progate",
      date: "2021",
      image: "/images/cert-9.png",
    },
    {
      id: 10,
      title: "Web Development Node.js",
      issuedBy: "Progate",
      date: "2021",
      image: "/images/cert-10.png",
    },
    {
      id: 11,
      title: "Database Design",
      issuedBy: "Oracle Academy",
      date: "2022",
      image: "/images/cert-11.png",
    },
    {
      id: 12,
      title: "Database Programming With SQL",
      issuedBy: "Oracle Academy",
      date: "2022",
      image: "/images/cert-12.png",
    },
    {
      id: 13,
      title: "Responsive Web Design",
      issuedBy: "FreeCodeCamp",
      date: "2021",
      image: "/images/cert-13.png",
    },
    {
      id: 14,
      title: "Administration",
      issuedBy: "PT TANDONMAS MANDIRI",
      date: "2018",
      image: "/images/cert-14.png",
    },
  ]
  